services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../app:/app/app
    env_file: # load local variables
      - .env
    environment: # overwrite variables
      - APP_NAME
      - APP_ENV
      - DATABASE_URL
      - SECRET_KEY
      - DEBUG